/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tentamen_shane;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author shane
 */
public class GUI extends javax.swing.JFrame {

    public String input;
    public String ouput;
    
    
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pathField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainArea = new javax.swing.JTextArea();
        browseButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();
        pathLabel = new javax.swing.JLabel();
        dataLabel = new javax.swing.JLabel();
        filenameLabel = new javax.swing.JLabel();
        fileLabel = new javax.swing.JLabel();
        visionButton = new javax.swing.JButton();
        stageBackgroundPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        letter2Label = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        letter1Label = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        letter3Label = new javax.swing.JLabel();
        percent2Label = new javax.swing.JLabel();
        percent1Label = new javax.swing.JLabel();
        percent3Label = new javax.swing.JLabel();
        headerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pathField.setForeground(new java.awt.Color(119, 119, 119));
        pathField.setText("Click browse to begin");
        pathField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathFieldActionPerformed(evt);
            }
        });

        mainArea.setColumns(20);
        mainArea.setLineWrap(true);
        mainArea.setRows(5);
        jScrollPane1.setViewportView(mainArea);

        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        openButton.setText("Open File");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        pathLabel.setText("File Path:");

        dataLabel.setText("Data:");

        filenameLabel.setText("Filename:");

        fileLabel.setText("Choose File.");

        visionButton.setText("Visualize");
        visionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visionButtonActionPerformed(evt);
            }
        });

        stageBackgroundPanel.setBackground(new java.awt.Color(177, 177, 177));

        jPanel1.setBackground(new java.awt.Color(232, 232, 232));

        letter2Label.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        letter2Label.setText("X");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(letter2Label)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(letter2Label)
                .addGap(21, 21, 21))
        );

        jPanel2.setBackground(new java.awt.Color(255, 223, 33));

        letter1Label.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        letter1Label.setText("X");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(letter1Label)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(letter1Label)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(191, 112, 33));

        letter3Label.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        letter3Label.setText("X");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(letter3Label)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(letter3Label)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        percent2Label.setText("xx%");

        percent1Label.setText("xx%");

        percent3Label.setText("xx%");

        javax.swing.GroupLayout stageBackgroundPanelLayout = new javax.swing.GroupLayout(stageBackgroundPanel);
        stageBackgroundPanel.setLayout(stageBackgroundPanelLayout);
        stageBackgroundPanelLayout.setHorizontalGroup(
            stageBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stageBackgroundPanelLayout.createSequentialGroup()
                .addGroup(stageBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stageBackgroundPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stageBackgroundPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(percent2Label)
                        .addGap(40, 40, 40)))
                .addGroup(stageBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stageBackgroundPanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(stageBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(stageBackgroundPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(stageBackgroundPanelLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(percent3Label))))
                    .addGroup(stageBackgroundPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(percent1Label)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        stageBackgroundPanelLayout.setVerticalGroup(
            stageBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stageBackgroundPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(stageBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(stageBackgroundPanelLayout.createSequentialGroup()
                        .addComponent(percent1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(stageBackgroundPanelLayout.createSequentialGroup()
                        .addComponent(percent2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(stageBackgroundPanelLayout.createSequentialGroup()
                        .addComponent(percent3Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        headerLabel.setText("Header from File");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pathLabel)
                            .addComponent(dataLabel)
                            .addComponent(filenameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pathField, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(browseButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fileLabel)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(openButton)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(visionButton))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(headerLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(stageBackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pathLabel)
                    .addComponent(browseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filenameLabel)
                            .addComponent(fileLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(openButton)
                        .addGap(18, 18, 18)
                        .addComponent(visionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stageBackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        FileReader r1 = new FileReader();
        String path;
        path = pathField.getText();
        
        mainArea.setText(r1.FileReader(path));
        headerLabel.setText(r1.getHeader());
    }//GEN-LAST:event_openButtonActionPerformed

    private void pathFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathFieldActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        FileChooser f1 = new FileChooser();
        f1.Chooser();
        
        pathField.setText(f1.getPath());
        fileLabel.setText(f1.getFileName());

    }//GEN-LAST:event_browseButtonActionPerformed

    private void visionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visionButtonActionPerformed
        try {
            CodeLogic c1 = new CodeLogic();
            
            input = mainArea.getText().toUpperCase();
            ouput = c1.DNA(input);
            
            
            letter1Label.setText(c1.getFirst());
            letter2Label.setText(c1.getSecond());
            letter3Label.setText(c1.getThird());
            
            percent1Label.setText(Integer.toString(c1.getFirstPerc())+"%");
            percent2Label.setText(Integer.toString(c1.getSecondPerc())+"%");
            percent3Label.setText(Integer.toString(c1.getThirdPerc())+"%");
            
            
            
            
        } catch (NotAnAA ex) {
            System.out.println("Dit is geen bestaan aminozuur!");
        }
        
    }//GEN-LAST:event_visionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButton;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JLabel filenameLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel letter1Label;
    private javax.swing.JLabel letter2Label;
    private javax.swing.JLabel letter3Label;
    private javax.swing.JTextArea mainArea;
    private javax.swing.JButton openButton;
    private javax.swing.JTextField pathField;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JLabel percent1Label;
    private javax.swing.JLabel percent2Label;
    private javax.swing.JLabel percent3Label;
    private javax.swing.JPanel stageBackgroundPanel;
    private javax.swing.JButton visionButton;
    // End of variables declaration//GEN-END:variables
}
